#!/usr/bin/env node
// Regenerate src/tv-grid.generated.json, the lot sizes TradingView reports for Binance symbols,
// from a table of TradingView's own syminfo receipts (schema pineforge-tv-syminfo-receipts/v1):
//
//   node scripts/sync-tv-grid.mjs <path to tv-grid-table.json>
//
// Only the two Binance venues are read, and only each symbol's `mincontract`; the output is
// deterministic (sorted, one symbol per line), so re-running on the same table changes nothing.
// A table that is not complete, or has a value outside 1e-12..1e12, is refused, not trimmed.
// `--out <path>` writes elsewhere (the tests do).
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const SOURCE_SCHEMA = "pineforge-tv-syminfo-receipts/v1";
const OUTPUT_SCHEMA = "pineforge-tv-grid/v1";
const MARKETS = { spot: "crypto.binance.com.spot", usdt_perp: "crypto.binance.com.perp-usdt" };
const DEFAULT_OUT = fileURLToPath(new URL("../src/tv-grid.generated.json", import.meta.url));

function fail(message) {
  process.stderr.write(`sync-tv-grid: ${message}\n`);
  process.exit(1);
}

const args = process.argv.slice(2);
let out = DEFAULT_OUT;
const outAt = args.indexOf("--out");
if (outAt >= 0) {
  out = args[outAt + 1] ?? fail("--out needs a path");
  args.splice(outAt, 2);
}
if (args.length !== 1) fail("usage: node scripts/sync-tv-grid.mjs <path to tv-grid-table.json> [--out <path>]");

const bytes = readFileSync(args[0]);
let table;
try {
  table = JSON.parse(bytes.toString("utf8"));
} catch (e) {
  fail(`${args[0]} is not JSON: ${e.message}`);
}
if (table?.schema !== SOURCE_SCHEMA) fail(`${args[0]} is not a ${SOURCE_SCHEMA} table (schema ${JSON.stringify(table?.schema)})`);
if (table.complete !== true) fail(`${args[0]} is not complete (its "complete" is ${JSON.stringify(table.complete)}): it is still being refreshed`);
if (typeof table.generated_utc !== "string" || !/^\d{4}-\d\d-\d\dT[\d:.]+Z$/.test(table.generated_utc)) {
  fail(`${args[0]} has no generated_utc`);
}

const grids = {};
for (const [market, venue] of Object.entries(MARKETS)) {
  const rows = table.rows?.[venue];
  if (typeof rows !== "object" || rows === null || Array.isArray(rows)) fail(`${args[0]} has no rows for ${venue}`);
  const bad = [];
  const entries = [];
  for (const symbol of Object.keys(rows).sort()) {
    const value = rows[symbol]?.mincontract;
    const ok = typeof value === "number" && Number.isFinite(value) && value >= 1e-12 && value <= 1e12 &&
      /^[\x21-\x7e]{1,64}$/.test(symbol);
    if (ok) entries.push([symbol, value]);
    else bad.push(`${symbol}=${JSON.stringify(rows[symbol]?.mincontract)}`);
  }
  if (bad.length) fail(`${venue}: ${bad.length} rows without a usable mincontract (${bad.slice(0, 5).join(", ")}${bad.length > 5 ? ", ..." : ""})`);
  if (entries.length === 0) fail(`${venue} has no rows`);
  grids[market] = entries;
}

// What the maps hold, as text, for the hash that lets a test notice a hand edit.
const canonical = Object.keys(MARKETS)
  .map((m) => `${m}\n${grids[m].map(([s, v]) => `${s}=${v}\n`).join("")}`)
  .join("");

const block = (entries) => `{\n${entries.map(([s, v]) => `    ${JSON.stringify(s)}: ${JSON.stringify(v)}`).join(",\n")}\n  }`;
const text =
  "{\n" +
  `  "schema": ${JSON.stringify(OUTPUT_SCHEMA)},\n` +
  `  "_comment": "Generated by scripts/sync-tv-grid.mjs from TradingView's own syminfo.mincontract; do not edit.",\n` +
  `  "source": ${JSON.stringify({
    schema: SOURCE_SCHEMA,
    generated_utc: table.generated_utc,
    sha256: createHash("sha256").update(bytes).digest("hex"),
    venues: MARKETS,
  })},\n` +
  `  "counts": ${JSON.stringify(Object.fromEntries(Object.keys(MARKETS).map((m) => [m, grids[m].length])))},\n` +
  `  "content_sha256": ${JSON.stringify(createHash("sha256").update(canonical).digest("hex"))},\n` +
  `  "spot": ${block(grids.spot)},\n` +
  `  "usdt_perp": ${block(grids.usdt_perp)}\n` +
  "}\n";
writeFileSync(out, text);
process.stdout.write(
  `wrote ${out}: spot ${grids.spot.length}, usdt_perp ${grids.usdt_perp.length} symbols, ` +
  `source ${table.generated_utc} sha256 ${createHash("sha256").update(bytes).digest("hex").slice(0, 12)}\n`,
);
