//@version=6
strategy("Minimal Long", initial_capital=10000, default_qty_type=strategy.percent_of_equity, default_qty_value=100, commission_type=strategy.commission.percent, commission_value=0.1, margin_long=100, margin_short=100, pyramiding=0)
fastAverage = ta.sma(close, 5)
slowAverage = ta.sma(close, 20)
if ta.crossover(fastAverage, slowAverage)
    strategy.entry("Long", strategy.long)
if ta.crossunder(fastAverage, slowAverage)
    strategy.close("Long")
